SET (TEST_BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")

GET_FILENAME_COMPONENT (TBD_NAME ${TEST_BASE_DIR} NAME)
IF (NOT TBD_NAME STREQUAL "test")
    MESSAGE (SEND_ERROR "You should include module Test.cmake from directory with tests")
ENDIF ()
GET_FILENAME_COMPONENT (TBD_PARENT ${TEST_BASE_DIR} PATH)
GET_FILENAME_COMPONENT (TBD_PARENT_NAME ${TBD_PARENT} NAME)

INCLUDE (output_paths)

FIND_FILE (TEST_STD_CONFIG "test_std_config.h.in" ${CMAKE_MODULE_PATH} NO_CMAKE_FIND_ROOT_PATH)
CONFIGURE_FILE ("${TEST_STD_CONFIG}" "${AUTO_INCLUDE_DIR}/${TBD_PARENT_NAME}/test_std_config.h")
INCLUDE_DIRECTORIES (BEFORE "${AUTO_INCLUDE_DIR}/${TBD_PARENT_NAME}")

MACRO (ADD_UNIT_TEST TARGET_NAME)
    SET_TARGET_PROPERTIES (${TARGET_NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/unit_tests)
    ADD_TEST (NAME ${TARGET_NAME} COMMAND ${TARGET_NAME})
ENDMACRO()

SET (CPP_TEST_REPORT_TARGET_NAME "gen-cpp-test-report")
SET (CPP_TEST_REPORT_FILE_NAME  "${CMAKE_BINARY_DIR}/Testing/cpp_test_report.xml")

IF (NOT TARGET ${CPP_TEST_REPORT_TARGET_NAME})
    ADD_CUSTOM_TARGET (
            ${CPP_TEST_REPORT_TARGET_NAME}
            COMMAND ${CMAKE_SOURCE_DIR}/bin/generate_test_report.py
            -I "${CMAKE_BINARY_DIR}/Testing/Temporary/LastTest.log"
            -O "${CPP_TEST_REPORT_FILE_NAME}"
    )
ENDIF()
